### ISSUE TITLE
Crash after startup

### ISSUE THREAD

**Issue by Muffexx** [Fanman03/JackNetRGBSync#10]
The app crashes after startup.

My components with RGB:

- MoBo: ASUS Strix X570-E
- RAM: HyperX Fury
- Keyboard: Logitech Pro

rgbsync.log:

> 2020-05-04 11:58:52.6192|DEBUG|RGBSyncPlus.ApplicationManager|============ JackNet RGB Sync is Starting ============
2020-05-04 11:58:52.6402|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\Interop.AuraServiceLib.dll
2020-05-04 11:58:52.6522|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll
2020-05-04 11:58:57.3132|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll has been loaded
2020-05-04 11:58:57.3132|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll
2020-05-04 11:58:57.4833|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll has been loaded
2020-05-04 11:58:57.4833|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll
2020-05-04 11:58:57.4963|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll has been loaded
2020-05-04 11:58:57.4963|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.EVGA.dll
2020-05-04 11:59:02.5614|ERROR|RGBSyncPlus.ApplicationManager|Error loading C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.EVGA.dll
2020-05-04 11:59:02.5614|ERROR|RGBSyncPlus.ApplicationManager|System.Exception: Coudln't connect to EVGAProxy
   at RGB.NET.Devices.EVGA.EVGADeviceProvider..ctor()
   at RGB.NET.Devices.EVGA.EVGADeviceProvider.get_Instance()
   at RGB.NET.Devices.EVGA.EVGADeviceProviderLoader.GetDeviceProvider()
   at RGB.NET.Core.RGBSurface.LoadDevices(IRGBDeviceProviderLoader deviceProviderLoader, RGBDeviceType loadFilter, Boolean exclusiveAccessIfPossible, Boolean throwExceptions)
   at RGBSyncPlus.ApplicationManager.LoadDeviceProviders()
2020-05-04 11:59:02.5724|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Logitech.dll
2020-05-04 11:59:02.6144|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Logitech.dll has been loaded
2020-05-04 11:59:02.6184|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Novation.dll
2020-05-04 11:59:02.6184|ERROR|RGBSyncPlus.ApplicationManager|Error loading C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Novation.dll
2020-05-04 11:59:02.6184|ERROR|RGBSyncPlus.ApplicationManager|System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at RGBSyncPlus.ApplicationManager.LoadDeviceProviders()
2020-05-04 11:59:02.6184|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Razer.dll
2020-05-04 11:59:02.6454|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Razer.dll has been loaded
2020-05-04 11:59:02.6504|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\user\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.WS281X.dll
2020-05-04 11:59:02.6504|INFO|RGBSyncPlus.ApplicationManager|Discord RPC enabled.
2020-05-04 11:59:02.6504|INFO|RGBSyncPlus.ApplicationManager|Setting Discord presensce.
2020-05-04 11:59:03.1285|INFO|RGBSyncPlus.ApplicationManager|Checking for update...
2020-05-04 11:59:03.3416|DEBUG|RGBSyncPlus.ApplicationManager|============ App is Shutting Down ============
2020-05-04 11:59:03.6046|DEBUG|RGBSyncPlus.ApplicationManager|============ App is Shutting Down ============

error.log

> [04.05.2020 11:59:03] Exception!
Message:
The remote server returned an error: (521) Origin Down.
StackTrace:
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at RGBSyncPlus.ApplicationManager.OpenConfiguration()
   at RGBSyncPlus.Helper.ActionCommand.Execute(Object parameter)
   at RGBSyncPlus.App.OnStartup(StartupEventArgs e)

I can't figure it out.

Regards
Muffexx

**Comment by Fanman03** [comment]
Hi,

We experienced some downtime today due to a back-end server failure. The server has been restored to its online state, and all systems are now operational. Please let me know if this did not resolve your issue.

**Comment by Muffexx** [comment]
Hello Fanman03,

it's back to normal. Thank you for your answer.

Regards
Muffexx
