### ISSUE TITLE
Crashing when clicking on Tray Icon

### ISSUE THREAD

**Issue by alwe2710** [Fanman03/JackNetRGBSync#8]
Whenever I try to click on the tray icon it disappears but no GUI appears (I assume it crashes)

**Comment by mad-it** [comment]
I have the same on the latest version, 1.7.6.

Here are some logs:

rgbsync.log content:
```
2020-03-31 17:11:40.4304|DEBUG|RGBSyncPlus.ApplicationManager|============ JackNet RGB Sync is Starting ============
2020-03-31 17:11:40.4544|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\HidSharp.dll
2020-03-31 17:11:40.4665|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\Interop.AuraServiceLib.dll
2020-03-31 17:11:40.4745|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll
2020-03-31 17:11:43.3982|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll has been loaded
2020-03-31 17:11:43.3982|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll
2020-03-31 17:11:43.5185|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll has been loaded
2020-03-31 17:11:43.5255|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll
2020-03-31 17:11:43.5440|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll has been loaded
2020-03-31 17:11:43.5440|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.EVGA.dll
2020-03-31 17:11:48.6195|ERROR|RGBSyncPlus.ApplicationManager|Error loading C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.EVGA.dll
2020-03-31 17:11:48.6195|ERROR|RGBSyncPlus.ApplicationManager|System.Exception: Coudln't connect to EVGAProxy
   at RGB.NET.Devices.EVGA.EVGADeviceProvider..ctor()
   at RGB.NET.Devices.EVGA.EVGADeviceProvider.get_Instance()
   at RGB.NET.Devices.EVGA.EVGADeviceProviderLoader.GetDeviceProvider()
   at RGB.NET.Core.RGBSurface.LoadDevices(IRGBDeviceProviderLoader deviceProviderLoader, RGBDeviceType loadFilter, Boolean exclusiveAccessIfPossible, Boolean throwExceptions)
   at RGBSyncPlus.ApplicationManager.LoadDeviceProviders()
2020-03-31 17:11:48.6375|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Logitech.dll
2020-03-31 17:11:48.6526|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Logitech.dll has been loaded
2020-03-31 17:11:48.6526|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Msi.dll
2020-03-31 17:11:58.7416|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Msi.dll has been loaded
2020-03-31 17:11:58.7416|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Novation.dll
2020-03-31 17:11:58.7576|ERROR|RGBSyncPlus.ApplicationManager|Error loading C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Novation.dll
2020-03-31 17:11:58.7576|ERROR|RGBSyncPlus.ApplicationManager|System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at RGBSyncPlus.ApplicationManager.LoadDeviceProviders()
2020-03-31 17:11:58.7706|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Razer.dll
2020-03-31 17:11:58.7866|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Razer.dll has been loaded
2020-03-31 17:11:58.7866|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Roccat.dll
2020-03-31 17:11:58.8026|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Roccat.dll has been loaded
2020-03-31 17:11:58.8026|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.SteelSeries.dll
2020-03-31 17:11:58.8577|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.SteelSeries.dll has been loaded
2020-03-31 17:11:58.8647|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.WS281X.dll
2020-03-31 17:11:58.8647|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Mad\AppData\Roaming\JackNet RGB Sync\DeviceProvider\System.ValueTuple.dll
2020-03-31 17:11:58.9875|DEBUG|RGBSyncPlus.ApplicationManager|============ App is Shutting Down ============
```

error.log content:
```
[3/31/2020 5:11:58 PM] Exception!

Message:
Method 'GetColorAtPoint' in type 'RGBSyncPlus.Brushes.SyncBrush' from assembly 'RGBSync+, Version=1.7.6.21554, Culture=neutral, PublicKeyToken=null' does not have an implementation.

StackTrace:
   at RGBSyncPlus.ApplicationManager.RegisterSyncGroup(SyncGroup syncGroup)
   at RGBSyncPlus.ApplicationManager.Initialize()
   at RGBSyncPlus.App.OnStartup(StartupEventArgs e)
```

**Comment by Fanman03** [comment]
I have received this bug report from a few users now, can you please specify what hardware you are trying to sync and what versions of their respective control applications you are using?

**Comment by mad-it** [comment]
@Fanman03 I cannot say about the OP, but my own configuration is:
Corshair H150i running iCUE 2.23.66
Asus  ROG Strix x570-e not running Armor Crate/AURA since RGBSync does not see it as a master LED to sync with.

I reverted back to 1.6.2 as this was the last version working for me.

**Comment by alwe2710** [comment]
Thats my rgbsync.log:
`2020-04-10 00:19:07.5200|DEBUG|RGBSyncPlus.ApplicationManager|============ JackNet RGB Sync is Starting ============
2020-04-10 00:19:07.5418|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\HidSharp.dll
2020-04-10 00:19:07.5800|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\Interop.AuraServiceLib.dll
2020-04-10 00:19:07.5949|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll
2020-04-10 00:19:09.9043|DEBUG|RGBSyncPlus.ApplicationManager|============ JackNet RGB Sync is Starting ============
2020-04-10 00:19:09.9296|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\HidSharp.dll
2020-04-10 00:19:09.9425|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\Interop.AuraServiceLib.dll
2020-04-10 00:19:09.9425|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll
2020-04-10 00:19:11.7360|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll has been loaded
2020-04-10 00:19:11.7395|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll
2020-04-10 00:19:13.4090|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll has been loaded
2020-04-10 00:19:13.4090|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll
2020-04-10 00:19:14.9783|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll has been loaded
2020-04-10 00:19:14.9783|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll
2020-04-10 00:19:16.8205|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll has been loaded
2020-04-10 00:19:16.8205|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll
2020-04-10 00:22:36.9177|DEBUG|RGBSyncPlus.ApplicationManager|============ JackNet RGB Sync is Starting ============
2020-04-10 00:22:36.9434|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\HidSharp.dll
2020-04-10 00:22:36.9563|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\Interop.AuraServiceLib.dll
2020-04-10 00:22:36.9563|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll
2020-04-10 00:22:41.5964|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll has been loaded
2020-04-10 00:22:41.5964|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll
2020-04-10 00:22:43.7788|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll has been loaded
2020-04-10 00:22:43.7858|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll
2020-04-10 00:24:13.5983|DEBUG|RGBSyncPlus.ApplicationManager|============ JackNet RGB Sync is Starting ============
2020-04-10 00:24:13.6282|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\HidSharp.dll
2020-04-10 00:24:13.6282|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\Interop.AuraServiceLib.dll
2020-04-10 00:24:13.6492|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll
2020-04-10 00:24:18.2679|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll has been loaded
2020-04-10 00:24:18.2729|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll
2020-04-10 00:24:20.3982|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll has been loaded
2020-04-10 00:24:20.3982|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll
2020-04-10 00:24:20.4172|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll has been loaded
2020-04-10 00:24:20.4172|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.EVGA.dll
2020-04-10 00:24:28.8742|DEBUG|RGBSyncPlus.ApplicationManager|============ JackNet RGB Sync is Starting ============
2020-04-10 00:24:28.9022|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\HidSharp.dll
2020-04-10 00:24:28.9141|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\Interop.AuraServiceLib.dll
2020-04-10 00:24:28.9141|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll
2020-04-10 00:24:33.5448|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll has been loaded
2020-04-10 00:24:33.5498|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll
2020-04-10 00:24:35.6836|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll has been loaded
2020-04-10 00:24:35.6906|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll
2020-04-10 00:24:35.6906|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll has been loaded
2020-04-10 00:24:35.7115|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\alwe2\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.EVGA.dll
`

**Comment by alwe2710** [comment]
I've got some news: If I unplug my Keyboard the Software opens. It has to be a driver-related issue. My keyboard is a CoolerMaster Masterkeys Pro L

**Comment by M4gus10** [comment]
Can confirm, i have the same keyboard and the app crashes as long as the keyboard is plugged in :(
If i unplug the keyboard it works fine

**Comment by jaycollett** [comment]
I can confirm I had the same crashing issue with the Razer Mouse driver/software installed. When I uninstalled and rebooted, the crashing stopped.

**Comment by gdmachado** [comment]
I'm experiencing the same issue, however no new hardware/software was installed on my end. Issue started happening afterupgrading to 1.7.6.

<details>
  <summary>rgbsync.log</summary>
  
  ```
2020-06-08 16:39:11.8431|DEBUG|RGBSyncPlus.ApplicationManager|============ JackNet RGB Sync is Starting ============
2020-06-08 16:39:11.9136|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\HidSharp.dll
2020-06-08 16:39:11.9711|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\Interop.AuraServiceLib.dll
2020-06-08 16:39:12.0236|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll
2020-06-08 16:39:15.0880|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Asus.dll has been loaded
2020-06-08 16:39:15.1390|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll
2020-06-08 16:39:15.3155|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.CoolerMaster.dll has been loaded
2020-06-08 16:39:15.3665|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll
2020-06-08 16:39:15.4290|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Corsair.dll has been loaded
2020-06-08 16:39:15.4800|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.EVGA.dll
2020-06-08 16:39:15.8085|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.EVGA.dll has been loaded
2020-06-08 16:39:15.8605|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Logitech.dll
2020-06-08 16:39:15.9590|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Logitech.dll has been loaded
2020-06-08 16:39:16.0105|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Msi.dll
2020-06-08 16:39:26.2594|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Msi.dll has been loaded
2020-06-08 16:39:26.3119|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Novation.dll
2020-06-08 16:39:26.3664|ERROR|RGBSyncPlus.ApplicationManager|Error loading C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Novation.dll
2020-06-08 16:39:26.4174|ERROR|RGBSyncPlus.ApplicationManager|System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at RGBSyncPlus.ApplicationManager.LoadDeviceProviders()
2020-06-08 16:39:26.4719|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Razer.dll
2020-06-08 16:39:26.5324|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Razer.dll has been loaded
2020-06-08 16:39:26.5839|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Roccat.dll
2020-06-08 16:39:26.6364|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.Roccat.dll has been loaded
2020-06-08 16:39:26.6869|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.SteelSeries.dll
2020-06-08 16:39:26.7674|DEBUG|RGBSyncPlus.ApplicationManager|C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.SteelSeries.dll has been loaded
2020-06-08 16:39:26.8184|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\RGB.NET.Devices.WS281X.dll
2020-06-08 16:39:26.8719|DEBUG|RGBSyncPlus.ApplicationManager|Loading provider C:\Users\Gustavo\AppData\Roaming\JackNet RGB Sync\DeviceProvider\System.ValueTuple.dll
2020-06-08 16:39:27.0184|DEBUG|RGBSyncPlus.ApplicationManager|============ App is Shutting Down ============
  ```
</details>

<details>
  <summary>error.log</summary>
  
  ```
[6/8/2020 4:39:26 PM] Exception!

Message:
Method 'GetColorAtPoint' in type 'RGBSyncPlus.Brushes.SyncBrush' from assembly 'RGBSync+, Version=1.7.6.21554, Culture=neutral, PublicKeyToken=null' does not have an implementation.

StackTrace:
   at RGBSyncPlus.ApplicationManager.RegisterSyncGroup(SyncGroup syncGroup)
   at RGBSyncPlus.ApplicationManager.Initialize()
   at RGBSyncPlus.App.OnStartup(StartupEventArgs e)

  ```
</details>

My configuration:
- iCUE 3.29.110
- MB: Asus Strix x570-E
- JackNet was controlling a couple RGB strips, RAM and mobo leds

**Comment by Naamloos** [comment]
Same issue happens even with my Masterkeys white.
My fix was:
1. Unplug keyboard.
2. Launch Jacknet.
3. Use device exclude tool
4. replug keyboard

Might not be favorable with RGB keyboard, but for white LEDs it's a solution in my eyes.
